# Generated by Django 2.1.4 on 2018-12-06 14:06

from django.db import migrations

PRODUCTS = [
    {
        'name': 'FLYER FOR INVITATION',
        'price': 60,
        'slug': 'item-1',
        'description': 'flyer invitation'
    },
    {
        'name': 'Regular TICKET',
        'price': 60,
        'slug': 'item-2',
        'description': 'One Day Network Soiree Ticket Saturday'
    },

    {
        'name': 'VIP TICKET',
        'price': 250,
        'slug': 'item-3',
        'description': 'Two Day Network Access Ticket Friday - Saturday'
    },
    {
        'name': 'donation ',
        'price': 1,
        'slug': 'item-4',
        'description': 'Donation'
    },


]


def add_products(apps, schema_editor):
    Product = apps.get_model('ecommerce_app', 'Product')

    for p in PRODUCTS:
        l = Product.objects.get_or_create(
            name = p['name'],
            price = p['price'],
            slug = p['slug'],
            description = p['description'],
        )

        print(p)


def remove_products(apps, schema_editor):
    Product = apps.get_model('ecommerce_app', 'Product')

    for p in PRODUCTS:
        l = Product.objects.get(
            slug=p['slug'],
        )

        l.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_products, remove_products)
    ]
