# Generated by Django 4.0.4 on 2022-05-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_auto_20181206_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='agree',
            field=models.BooleanField(default=False, verbose_name='I Agree to policy'),
        ),
    ]
