# Generated by Django 4.0.4 on 2022-05-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0004_cartitem_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
    ]
