# Generated by Django 4.0.4 on 2022-05-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0005_alter_cartitem_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='user_email',
            field=models.CharField(max_length=25),
        ),
    ]
